title: Home
button_card_templates: !include_dir_merge_named "templates/internal_templates/"

views: !include_dir_list "views/"

kiosk_mode:
  non_admin_settings:
    hide_header: true
    ignore_entity_settings: true
  mobile_settings:
    hide_header: true